version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - revive
    - bodyclose
    - gosec

issues:
  exclude-use-default: false
  exclude-dirs:
    - docker
  max-issues-per-linter: 0
  max-same-issues: 0